#!/bin/bash
# Não era para existir

mkdir logs

chmod +x ~/binder/start.hadoop 
chmod +x ~/binder/start.hive 
chmod +x ~/binder/start.hbase 

chmod +x ~/binder/start.redis 
chmod +x ~/binder/start.postgresql

chmod +x ~/binder/start.vscode 

# starting redis in parallel
~/binder/start.redis &

# starting postgresql in parallel
~/binder/start.postgresql &

# starting vscode in parallel
~/binder/start.vscode  &

# Starting big data environment and waiting for it to be ready
echo "Starting Big Data services in the background..."
(
    ~/binder/start.hadoop  && \
    sleep 3                && \
    ~/binder/start.hive    && \
    ~/binder/start.hbase   && \
    touch ready
) &

# Wait for the 'ready' file to be created, which signals that services are up
echo "Waiting for Big Data environment to initialize..."
while [ ! -f ready ]; do
    echo "Still waiting for services to start..."
    sleep 5
done
echo "Big Data environment is ready!"

cd ~
echo " " >> .gitignore
echo "resources/local/" >> .gitignore
echo ".local/" >> .gitignore
echo "local-home/" >> .gitignore


# adding my own extensions
mkdir -p ~/.ipython/extensions/
cp       ~/.ipython/extensions/* ~/.ipython/extensions/


# DO NOT REMOVE(!) 
# Here is why: https://mybinder.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"
